version: '3.4'

services:
  azurefunc:
    image: ${DOCKER_REGISTRY-}handmadenewsazurefunc
    build:
      context: .
      dockerfile: HandmadeNews.AzureFunc/Dockerfile
    ports:
      - "34895:34895"
    depends_on:
        - db 
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql 
